## Linear reression with multiple variable

In [8]:

import pandas as pd
import numpy as np
from sklearn import linear_model

In [11]:
df=pd.read_csv("homeprices2.csv")
df


area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      NaN   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [14]:
import math

median_bedrooms=math.floor(df.bedroom.median())

median_bedrooms

3

In [17]:
df.bedroom=df.bedroom.fillna(median_bedrooms)

In [18]:
df

area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      3.0   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [20]:
reg=linear_model.LinearRegression()
reg.fit(df[['area','bedroom','age']],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [21]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [23]:
reg.intercept_

383724.99999999994

In [24]:
reg.predict([[3000,3,40]])

array([444400.])

In [25]:
reg.predict([[3000,3,15]])

array([615025.])