08-08-2020

In [1]:
import pandas as pd


In [2]:
data= pd.read_csv('iris.csv',names=['sl','sw','pl','pw','classes'])

In [3]:
data.head()

sl   sw   pl   pw      classes
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [4]:
x_feature=data.iloc[:,0:4]
y_label=data['classes']
x_feature

sl   sw   pl   pw
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [5]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [6]:
x_train,x_test,y_train,y_test=train_test_split(x_feature,y_label,test_size=.2,random_state=10)

In [7]:
data.shape

(150, 5)

In [8]:
x_train.shape


(120, 4)

In [9]:
x_test.shape


(30, 4)

In [10]:
y_train.shape


(120,)

In [11]:
y_test.shape

(30,)

In [12]:
print(y_train)

58     Iris-versicolor
97     Iris-versicolor
129     Iris-virginica
114     Iris-virginica
146     Iris-virginica
            ...       
113     Iris-virginica
64     Iris-versicolor
15         Iris-setosa
125     Iris-virginica
9          Iris-setosa
Name: classes, Length: 120, dtype: object


In [13]:
print(x_train)

      sl   sw   pl   pw
58   6.6  2.9  4.6  1.3
97   6.2  2.9  4.3  1.3
129  7.2  3.0  5.8  1.6
114  5.8  2.8  5.1  2.4
146  6.3  2.5  5.0  1.9
..   ...  ...  ...  ...
113  5.7  2.5  5.0  2.0
64   5.6  2.9  3.6  1.3
15   5.7  4.4  1.5  0.4
125  7.2  3.2  6.0  1.8
9    4.9  3.1  1.5  0.1

[120 rows x 4 columns]


In [14]:
knn=KNeighborsClassifier(n_neighbors=5)

In [15]:
knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [16]:
predict=knn.predict(x_test)

In [17]:
print(predict)

['Iris-versicolor' 'Iris-virginica' 'Iris-setosa' 'Iris-versicolor'
 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor'
 'Iris-setosa' 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica'
 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa' 'Iris-virginica'
 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-setosa'
 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-virginica']


In [18]:
test_data=pd.DataFrame([[6.4,2.9,4.3,1.3]])

In [19]:
print(knn.predict(test_data))

['Iris-versicolor']


In [20]:
print(confusion_matrix(y_test,predict))

[[10  0  0]
 [ 0 12  1]
 [ 0  0  7]]


In [21]:
print(accuracy_score(y_test,predict))

0.9666666666666667


# doing same using mathematically

Formula: sqrt(square(O-A)+square(O-A))
Where:-
    O: Observe data
    A: Actual data

1. calculate 150 row distance with formula
2. sort in ascending order
3. create group of 5 neighbor
4. count same group
5. sort on descending order

print(top sorted record as prediction

In [22]:
import pandas as pd
import numpy as np
import math
import operator


In [23]:
data= pd.read_csv('iris.csv',names=['sl','sw','pl','pw','classes'])

In [24]:
def ed(data1,data2,length):
    distance=0
    for x in range(length):
        distance=np.square(data1[x]-data2[x])
    return np.sqrt(distance)


In [25]:
# test=pd.DataFrame([[4.8,3,1.4,0.1]])
# test.shape
# data.shape
# for x in range(150):
#     print(ed(data.iloc[x],test,4))

In [27]:
# Defining our KNN model
def knn(trainset, testset, k):
    distances = {}
    sort = {}
    
    length = testset.shape[1]
    
    # Calculating distance using ed function and store in dictonary 
    for x in range(len(trainset)):
        dist = ed(testset,trainset.iloc[x], length)
        distances[x] = dist[0]
       
    #sorting in ascending by assigning value as a 'key' in distance dictonary
    sorted_d = sorted(distances.items(), 
                      key=operator.itemgetter(1))
    # list to create groups of K values
    neighbors = [] 
    
    # Extracting top k neighbors
    for x in range(k):
        neighbors.append(sorted_d[x][0])
        #[[1,2,3,4,5],[3,4,5,6,7]]
    #### End of STEP 3.3
    classVotes = {}
    # Calculating the most freq class in the neighbors
    for x in range(len(neighbors)):
        response = trainset.iloc[neighbors[x]][-1]
 
        if response in classVotes:
            classVotes[response] += 1
        else:
            classVotes[response] = 1
    sortedVotes = sorted(classVotes.items(),
    key=operator.itemgetter(1), reverse=True)
    return(sortedVotes[0][0])

In [28]:
test=pd.DataFrame([[4.8,3,1.4,0.1]])
k = 5
result = knn(data, test, k)
print(result)

Iris-setosa
